-- ============================================================
-- ARCA d'Ajuda — Livro de Atas
-- Correr UMA vez no Supabase: Dashboard → SQL Editor → New query → Run
-- Cria as duas tabelas que a página atas/ usa. A Direção continua a
-- vir das tabelas já existentes (direcao_membros + socios).
-- ============================================================

create table if not exists public.atas (
  id             bigint generated by default as identity primary key,
  numero         text,
  seq            integer,
  ano            integer,
  tipo           text,
  data           date,
  hora_inicio    text,
  hora_fim       text,
  local          text,
  presidiu       text,
  secretariou    text,
  presencas      jsonb default '[]'::jsonb,
  convidados     text,
  ausencias      text,
  ordem          jsonb default '[]'::jsonb,
  corpo          text default '',
  abertura_auto  boolean default true,
  fechada_em     timestamptz,
  reaberta       boolean default false,
  fechos         jsonb default '[]'::jsonb,
  reaberturas    jsonb default '[]'::jsonb,
  versoes        jsonb default '[]'::jsonb,
  drive_file_id  text,
  drive_em       timestamptz,
  criada_em      timestamptz default now(),
  atualizada_em  timestamptz default now()
);

-- (se a tabela já existia de uma instalação anterior, acrescenta as colunas do Drive)
alter table public.atas add column if not exists drive_file_id text;
alter table public.atas add column if not exists drive_em timestamptz;

-- PIN de cada membro da Direção (chave = n.º de sócio, o mesmo de direcao_membros.socio_num)
create table if not exists public.direcao_pins (
  socio_num      integer primary key,
  nome           text,
  pin_hash       text not null,
  atualizado_em  timestamptz default now()
);

-- Segurança: só utilizadores com sessão iniciada (a mesma conta das outras apps)
alter table public.atas         enable row level security;
alter table public.direcao_pins enable row level security;

drop policy if exists "atas_utilizadores_autenticados" on public.atas;
create policy "atas_utilizadores_autenticados"
  on public.atas for all to authenticated using (true) with check (true);

drop policy if exists "pins_utilizadores_autenticados" on public.direcao_pins;
create policy "pins_utilizadores_autenticados"
  on public.direcao_pins for all to authenticated using (true) with check (true);

-- Índices úteis
create index if not exists atas_ano_seq_idx on public.atas (ano desc, seq desc);
